In [54]:
import pandas as pd
df = pd.read_csv('test_fastapi/src/data/census.csv')
df.head()

age          workclass   fnlgt   education   education-num  \
0   39          State-gov   77516   Bachelors              13   
1   50   Self-emp-not-inc   83311   Bachelors              13   
2   38            Private  215646     HS-grad               9   
3   53            Private  234721        11th               7   
4   28            Private  338409   Bachelors              13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

    capital-gain   capital-loss   hours-per-week  native-country  salary  
0           2174              0               40   United-States   <=50K  
1              0              0               13   United-States   <=50K  
2              0              0               40   United-States   <=50K  
3              0              0               40   United-States   <=50K  
4              0              0               40            Cuba   <=50K

In [55]:
df.columns

Index(['age', ' workclass', ' fnlgt', ' education', ' education-num',
       ' marital-status', ' occupation', ' relationship', ' race', ' sex',
       ' capital-gain', ' capital-loss', ' hours-per-week', ' native-country',
       ' salary'],
      dtype='object')

In [56]:
x = np.array(0)
type(x)

numpy.ndarray

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   age              32561 non-null  int64 
 1    workclass       32561 non-null  object
 2    fnlgt           32561 non-null  int64 
 3    education       32561 non-null  object
 4    education-num   32561 non-null  int64 
 5    marital-status  32561 non-null  object
 6    occupation      32561 non-null  object
 7    relationship    32561 non-null  object
 8    race            32561 non-null  object
 9    sex             32561 non-null  object
 10   capital-gain    32561 non-null  int64 
 11   capital-loss    32561 non-null  int64 
 12   hours-per-week  32561 non-null  int64 
 13   native-country  32561 non-null  object
 14   salary          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [59]:
for col in df.columns:
    print(col, len(df[df[col] == 0]))

age 0
 workclass 0
 fnlgt 0
 education 0
 education-num 0
 marital-status 0
 occupation 0
 relationship 0
 race 0
 sex 0
 capital-gain 29849
 capital-loss 31042
 hours-per-week 0
 native-country 0
 salary 0


In [61]:
df.columns = df.columns.str.strip()
df.drop(['capital-gain', 'capital-loss'], axis=1, inplace=True)

In [62]:
import numpy as np
print(np.unique(df['workclass']))

[' ?' ' Federal-gov' ' Local-gov' ' Never-worked' ' Private'
 ' Self-emp-inc' ' Self-emp-not-inc' ' State-gov' ' Without-pay']


In [63]:
print(np.unique(df['education']))

[' 10th' ' 11th' ' 12th' ' 1st-4th' ' 5th-6th' ' 7th-8th' ' 9th'
 ' Assoc-acdm' ' Assoc-voc' ' Bachelors' ' Doctorate' ' HS-grad'
 ' Masters' ' Preschool' ' Prof-school' ' Some-college']


In [64]:
print(np.unique(df['education-num']))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [65]:
for col in df.drop(['age', 'fnlgt'], axis=1).columns:
    print(col, np.unique(df[col]))
    print()

workclass [' ?' ' Federal-gov' ' Local-gov' ' Never-worked' ' Private'
 ' Self-emp-inc' ' Self-emp-not-inc' ' State-gov' ' Without-pay']

education [' 10th' ' 11th' ' 12th' ' 1st-4th' ' 5th-6th' ' 7th-8th' ' 9th'
 ' Assoc-acdm' ' Assoc-voc' ' Bachelors' ' Doctorate' ' HS-grad'
 ' Masters' ' Preschool' ' Prof-school' ' Some-college']

education-num [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]

marital-status [' Divorced' ' Married-AF-spouse' ' Married-civ-spouse'
 ' Married-spouse-absent' ' Never-married' ' Separated' ' Widowed']

occupation [' ?' ' Adm-clerical' ' Armed-Forces' ' Craft-repair' ' Exec-managerial'
 ' Farming-fishing' ' Handlers-cleaners' ' Machine-op-inspct'
 ' Other-service' ' Priv-house-serv' ' Prof-specialty' ' Protective-serv'
 ' Sales' ' Tech-support' ' Transport-moving']

relationship [' Husband' ' Not-in-family' ' Other-relative' ' Own-child' ' Unmarried'
 ' Wife']

race [' Amer-Indian-Eskimo' ' Asian-Pac-Islander' ' Black' ' Other' ' White']

sex [' Female' 

In [66]:
len(np.unique(df['hours-per-week']))

94

In [67]:
from sklearn.metrics import fbeta_score, precision_score, recall_score
import logging
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split


In [68]:
df.columns

Index(['age', 'workclass', 'fnlgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'hours-per-week', 'native-country', 'salary'],
      dtype='object')

In [69]:
len(np.unique(df['fnlgt']))

21648

In [70]:
cat_features = [
    "workclass",
    "education",
    "marital-status",
    "occupation",
    "relationship",
    "race",
    "sex",
    "native-country",
]

In [71]:
from sklearn.preprocessing import LabelBinarizer, OneHotEncoder

In [72]:
y = df['salary']
X = df.drop('salary', axis=1)
X_categorical = X[cat_features].values
X_continuous = X.drop(*[cat_features], axis=1)
encoder = OneHotEncoder(sparse=False, handle_unknown="ignore")
lb = LabelBinarizer()
X_categorical = encoder.fit_transform(X_categorical)
y = lb.fit_transform(y.values).ravel()
X = np.concatenate([X_continuous, X_categorical], axis=1)

/Users/mkhair02/anaconda3/envs/fastapi/lib/python3.8/site-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [73]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [74]:
model = RandomForestClassifier()
model.fit(X_train, y_train)

RandomForestClassifier()

In [75]:
from sklearn.metrics import fbeta_score, precision_score, recall_score
preds = model.predict(X_test)
fbeta = fbeta_score(y_test, preds, beta=1, zero_division=1)
precision = precision_score(y_test, preds, zero_division=1)
recall = recall_score(y_test, preds, zero_division=1)

In [76]:
fbeta

0.6049083995852056

In [77]:
precision

0.6679389312977099

In [78]:
recall

0.5527479469361971

In [4]:
import pandas as pd
clean_df = pd.read_csv('census_cleaned.csv').drop('Unnamed: 0', axis=1)
clean_df.head()

age          workclass   education       marital-status  \
0   39          State-gov   Bachelors        Never-married   
1   50   Self-emp-not-inc   Bachelors   Married-civ-spouse   
2   38            Private     HS-grad             Divorced   
3   53            Private        11th   Married-civ-spouse   
4   28            Private   Bachelors   Married-civ-spouse   

           occupation    relationship    race      sex  hours-per-week  \
0        Adm-clerical   Not-in-family   White     Male              40   
1     Exec-managerial         Husband   White     Male              13   
2   Handlers-cleaners   Not-in-family   White     Male              40   
3   Handlers-cleaners         Husband   Black     Male              40   
4      Prof-specialty            Wife   Black   Female              40   

   native-country  salary  
0   United-States   <=50K  
1   United-States   <=50K  
2   United-States   <=50K  
3   United-States   <=50K  
4            Cuba   <=50K

In [9]:
from joblib import load
import numpy as np
y = np.array([])
cat_features = [
    "workclass",
    "education",
    "marital-status",
    "occupation",
    "relationship",
    "race",
    "sex",
    "native-country",
    ]
encoder = load('src/model/encoder.joblib')
X_categorical = clean_df[cat_features].values
X_continuous = clean_df.drop(*[cat_features], axis=1)
X_continuous = X_continuous.drop('salary', axis=1)
X_categorical = encoder.transform(X_categorical)
X = np.concatenate([X_continuous, X_categorical], axis=1)


In [13]:
y = clean_df['salary']
lb = load('src/model/lb.joblib')
y = lb.fit_transform(y.values).ravel()
y

array([0, 0, 0, ..., 0, 0, 1])

In [14]:
y

array([0, 0, 0, ..., 0, 0, 1])